#notify = ["java", "-cp", "/Users/ontic/Desktop/ONTIC/", "notify"]
notify = ["java", "-jar", "/Users/ontic/.codex/codex_notify.jar"]

approval_policy = "never"
model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
model_personality = "pragmatic"

[features]
rmcp_client = false
unified_exec = true

[mcp_servers.atlassian_rovo]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.atlassian.com/v1/mcp"]

[mcp_servers.gitlab]
command = "/opt/homebrew/bin/gitlab-mcp"

[projects."/Users/ontic/Desktop/ONTIC"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[profiles.cmd-gen]
model = "gpt-5.2-codex"
model_reasoning_effort = "low"
approval_policy = "never"

